image: registry.gitlab.com/mehrancodes/laravel-sample:latest
stages:
  - test

unit_test:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - php artisan migrate
    - vendor/bin/phpunit
    - php artisan test