image: jguyomard/laravel-php
stages:
  - test

unit_test:
  stage: test
  script:
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - cp .env.example .env
    - php artisan key:generate
    - phpunit --coverage-text --colors=never
    - php artisan test