image: lorisleiva/laravel-docker/tree/main/7.3
stages:
  - test

unit_test:
  stage: test
  script:
    - composer update
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate
    - phpunit --coverage-text --colors=never
    - php artisan test