image: jguyomard/laravel-php
stages:
  - test

unit_test:
  stage: test
  script:
    - composer install
    - cp .env.example .env
    - php artisan key:generate
    - php artisan config:cache
    - php artisan route:cache
    - php artisan migrate
    - php artisan test